<?php

namespace Database\Seeders;

use App\Models\TosaApplicant;
use Illuminate\Database\Seeder;

class TosaApplicantRealDataSeeder extends Seeder
{
    public function run(): void
    {
        $applicants = [
            [
                'sr_code' => '23-73068',
                'full_name' => 'SAMONTAÑEZ, CHARLES D.',
                'email' => '23-73068@g.batstate-u.edu.ph',
                'college' => 'College of Informatics and Computing Sciences',
                'program' => 'Bachelor of Science in Information Technology Major in Business Analytics Track',
                'year_level' => '4th Year',
                'gwa' => 1.12,
                'gwa_verified' => true,
                'academic_year' => '2025-2026',
                'organization_name' => 'Association of Computing Machinery (ACM)',
                'subsection' => 'accepted',
                'status' => 'submitted',
                'requirements' => [
                    'cv' => ['name' => 'CV_Samontanez_Charles.pdf', 'title' => 'Curriculum Vitae', 'path' => 'tosa/23-73068/cv.pdf', 'uploaded_at' => '2026-09-20 07:44:44'],
                    'good_moral' => ['name' => 'Good_Moral_Samontanez.pdf', 'title' => 'Good Moral Certificate', 'path' => 'tosa/23-73068/good_moral.pdf', 'uploaded_at' => '2026-09-20 07:45:02'],
                    'scholastic' => ['name' => 'Scholastic_Record_GWA_1.12.pdf', 'title' => 'Scholastic Record (GWA 1.12)', 'path' => 'tosa/23-73068/scholastic.pdf', 'uploaded_at' => '2026-09-20 07:45:08'],
                    'certificates' => ['name' => 'Proof_Certificates_Samontanez.pdf', 'title' => 'Certificates with proof of legitimacy', 'path' => 'tosa/23-73068/certificates.pdf', 'uploaded_at' => '2026-09-20 07:45:13'],
                    'application_docs' => ['name' => 'TOSA_Application_Form_Signed.pdf', 'title' => 'Complete application documents', 'path' => 'tosa/23-73068/application_docs.pdf', 'uploaded_at' => '2026-09-20 07:45:18'],
                ],
                'remarks' => 'Verified scholastic record: 1.12 GWA confirmed from Registration Services. President\'s Lister, CICS council executive, and lead author in regional tech symposia. Endorsed for Top 10 Outstanding Students.',
            ],
            [
                'sr_code' => '23-70834',
                'full_name' => 'VIVAS, MICHELLE G.',
                'email' => '23-70834@g.batstate-u.edu.ph',
                'college' => 'College of Informatics and Computing Sciences',
                'program' => 'Bachelor of Science in Information Technology Major in Business Analytics Track',
                'year_level' => '4th Year',
                'gwa' => 1.18,
                'gwa_verified' => true,
                'academic_year' => '2025-2026',
                'organization_name' => 'Junior Philippine Computer Society (JPCS)',
                'subsection' => 'screening',
                'status' => 'submitted',
                'requirements' => [
                    'cv' => ['name' => '01_CV_Vivas.pdf', 'title' => 'Curriculum Vitae', 'path' => 'tosa/23-70834/cv.pdf', 'uploaded_at' => '2026-09-21 08:39:44'],
                    'good_moral' => ['name' => '02_Good_Moral_Vivas.pdf', 'title' => 'Good Moral Certificate', 'path' => 'tosa/23-70834/good_moral.pdf', 'uploaded_at' => '2026-09-21 08:40:03'],
                    'scholastic' => ['name' => '03_Scholastic_Record_1.18.pdf', 'title' => 'Scholastic Record (GWA 1.18)', 'path' => 'tosa/23-70834/scholastic.pdf', 'uploaded_at' => '2026-09-21 08:40:13'],
                    'certificates' => ['name' => '04_Certificates_Vivas.pdf', 'title' => 'Certificates with proof of legitimacy', 'path' => 'tosa/23-70834/certificates.pdf', 'uploaded_at' => '2026-09-21 08:40:21'],
                    'application_docs' => ['name' => '05_Application_Dossier.pdf', 'title' => 'Complete application documents', 'path' => 'tosa/23-70834/application_docs.pdf', 'uploaded_at' => '2026-09-21 08:42:39'],
                ],
                'remarks' => 'Verified scholastic record: 1.18 GWA. Dean\'s Lister, active data science researcher, and community literacy outreach coordinator.',
            ],
            [
                'sr_code' => '23-70000',
                'full_name' => 'Ana Reyes',
                'email' => 'ana.reyes@g.batstate-u.edu.ph',
                'college' => 'College of Accountancy, Business, Economics and International Hospitality Management',
                'program' => 'BS Information Technology',
                'year_level' => '3rd Year',
                'gwa' => 1.22,
                'gwa_verified' => true,
                'academic_year' => '2025-2026',
                'organization_name' => 'CABEIHM Student Council',
                'subsection' => 'interview',
                'status' => 'submitted',
                'requirements' => [
                    'cv' => ['name' => 'CV_Reyes_Ana.pdf', 'title' => 'Curriculum Vitae', 'path' => 'tosa/23-70000/cv.pdf'],
                    'good_moral' => ['name' => 'Good_Moral_Reyes.pdf', 'title' => 'Good Moral Certificate', 'path' => 'tosa/23-70000/good_moral.pdf'],
                    'scholastic' => ['name' => 'TOR_Grades_1.22.pdf', 'title' => 'Scholastic Record (GWA 1.22)', 'path' => 'tosa/23-70000/scholastic.pdf'],
                    'certificates' => ['name' => 'Certificates_Reyes.pdf', 'title' => 'Certificates with proof of legitimacy', 'path' => 'tosa/23-70000/certificates.pdf'],
                    'application_docs' => ['name' => 'Application_Dossier_Signed.pdf', 'title' => 'Complete application documents', 'path' => 'tosa/23-70000/application_docs.pdf'],
                ],
                'remarks' => 'Scholastic record verified: 1.22 GWA. High honors standing, student council director for academic affairs.',
            ],
            [
                'sr_code' => '23-70001',
                'full_name' => 'Mark Santos',
                'email' => 'mark.santos@g.batstate-u.edu.ph',
                'college' => 'College of Arts and Sciences',
                'program' => 'BS Psychology',
                'year_level' => '3rd Year',
                'gwa' => 1.25,
                'gwa_verified' => true,
                'academic_year' => '2025-2026',
                'organization_name' => 'Psychological Society',
                'subsection' => 'screening',
                'status' => 'submitted',
                'requirements' => [
                    'cv' => ['name' => 'CV_Santos_Mark.pdf', 'title' => 'Curriculum Vitae', 'path' => 'tosa/23-70001/cv.pdf'],
                    'good_moral' => ['name' => 'Good_Moral_Santos.pdf', 'title' => 'Good Moral Certificate', 'path' => 'tosa/23-70001/good_moral.pdf'],
                    'scholastic' => ['name' => 'Scholastic_Record_1.25.pdf', 'title' => 'Scholastic Record (GWA 1.25)', 'path' => 'tosa/23-70001/scholastic.pdf'],
                    'certificates' => ['name' => 'Certificates_Santos.pdf', 'title' => 'Certificates with proof of legitimacy', 'path' => 'tosa/23-70001/certificates.pdf'],
                    'application_docs' => null,
                ],
                'remarks' => '1.25 GWA verified. Complete application documents pending signed form from college dean.',
            ],
            [
                'sr_code' => '23-70002',
                'full_name' => 'Liza Cruz',
                'email' => 'liza.cruz@g.batstate-u.edu.ph',
                'college' => 'College of Nursing and Allied Health Sciences',
                'program' => 'BS Nursing',
                'year_level' => '4th Year',
                'gwa' => 1.28,
                'gwa_verified' => true,
                'academic_year' => '2025-2026',
                'organization_name' => 'Red Cross Youth BatStateU',
                'subsection' => 'interview',
                'status' => 'submitted',
                'requirements' => [
                    'cv' => ['name' => 'CV_Cruz_Liza.pdf', 'title' => 'Curriculum Vitae', 'path' => 'tosa/23-70002/cv.pdf'],
                    'good_moral' => ['name' => 'Good_Moral_Cruz.pdf', 'title' => 'Good Moral Certificate', 'path' => 'tosa/23-70002/good_moral.pdf'],
                    'scholastic' => ['name' => 'Transcript_1.28.pdf', 'title' => 'Scholastic Record (GWA 1.28)', 'path' => 'tosa/23-70002/scholastic.pdf'],
                    'certificates' => ['name' => 'Certificates_Cruz.pdf', 'title' => 'Certificates with proof of legitimacy', 'path' => 'tosa/23-70002/certificates.pdf'],
                    'application_docs' => ['name' => 'Application_Dossier_Cruz.pdf', 'title' => 'Complete application documents', 'path' => 'tosa/23-70002/application_docs.pdf'],
                ],
                'remarks' => '1.28 GWA verified. Outstanding clinical rotation performance and community first-aid volunteerism.',
            ],
            [
                'sr_code' => '21-00002',
                'full_name' => 'Maria Santos',
                'email' => '21-00002@g.batstate-u.edu.ph',
                'college' => 'College of Arts and Sciences',
                'program' => 'BS Development Communication',
                'year_level' => '3rd Year',
                'gwa' => 1.32,
                'gwa_verified' => true,
                'academic_year' => '2025-2026',
                'organization_name' => 'Communicators Guild',
                'subsection' => 'pending',
                'status' => 'submitted',
                'requirements' => [
                    'cv' => ['name' => 'CV_Maria_Santos.pdf', 'title' => 'Curriculum Vitae', 'path' => 'tosa/21-00002/cv.pdf'],
                    'good_moral' => ['name' => 'Good_Moral_Maria.pdf', 'title' => 'Good Moral Certificate', 'path' => 'tosa/21-00002/good_moral.pdf'],
                    'scholastic' => ['name' => 'Grades_1.32.pdf', 'title' => 'Scholastic Record (GWA 1.32)', 'path' => 'tosa/21-00002/scholastic.pdf'],
                    'certificates' => ['name' => 'Certificates_Maria.pdf', 'title' => 'Certificates with proof of legitimacy', 'path' => 'tosa/21-00002/certificates.pdf'],
                    'application_docs' => null,
                ],
                'remarks' => '1.32 GWA verified. University publication editor and student advocate.',
            ],
            [
                'sr_code' => '23-70003',
                'full_name' => 'Jon Dela Cruz',
                'email' => 'jon.dela.cruz@g.batstate-u.edu.ph',
                'college' => 'College of Criminal Justice Education',
                'program' => 'BS Criminology',
                'year_level' => '3rd Year',
                'gwa' => 1.38,
                'gwa_verified' => true,
                'academic_year' => '2025-2026',
                'organization_name' => 'Criminology Students Association',
                'subsection' => 'screening',
                'status' => 'submitted',
                'requirements' => [
                    'cv' => ['name' => 'CV_DelaCruz_Jon.pdf', 'title' => 'Curriculum Vitae', 'path' => 'tosa/23-70003/cv.pdf'],
                    'good_moral' => ['name' => 'Good_Moral_Jon.pdf', 'title' => 'Good Moral Certificate', 'path' => 'tosa/23-70003/good_moral.pdf'],
                    'scholastic' => ['name' => 'Grades_1.38.pdf', 'title' => 'Scholastic Record (GWA 1.38)', 'path' => 'tosa/23-70003/scholastic.pdf'],
                    'certificates' => ['name' => 'Certificates_Jon.pdf', 'title' => 'Certificates with proof of legitimacy', 'path' => 'tosa/23-70003/certificates.pdf'],
                    'application_docs' => null,
                ],
                'remarks' => '1.38 GWA verified. Leadership role in campus safety corps.',
            ],
            [
                'sr_code' => '23-70004',
                'full_name' => 'Mia Flores',
                'email' => 'mia.flores@g.batstate-u.edu.ph',
                'college' => 'College of Teacher Education',
                'program' => 'Bachelor of Secondary Education Major in English',
                'year_level' => '2nd Year',
                'gwa' => 1.42,
                'gwa_verified' => true,
                'academic_year' => '2025-2026',
                'organization_name' => 'Future Educators Guild',
                'subsection' => 'returned',
                'status' => 'submitted',
                'requirements' => [
                    'cv' => ['name' => 'CV_Flores_Mia.pdf', 'title' => 'Curriculum Vitae', 'path' => 'tosa/23-70004/cv.pdf'],
                    'good_moral' => ['name' => 'Good_Moral_Mia.pdf', 'title' => 'Good Moral Certificate', 'path' => 'tosa/23-70004/good_moral.pdf'],
                    'scholastic' => ['name' => 'Grades_1.42.pdf', 'title' => 'Scholastic Record (GWA 1.42)', 'path' => 'tosa/23-70004/scholastic.pdf'],
                    'certificates' => null,
                    'application_docs' => null,
                ],
                'remarks' => '1.42 GWA. Returned for missing records office certified certificates.',
            ],
            [
                'sr_code' => '23-70005',
                'full_name' => 'Carlo Mendoza',
                'email' => 'carlo.mendoza@g.batstate-u.edu.ph',
                'college' => 'College of Accountancy, Business, Economics and International Hospitality Management',
                'program' => 'BSBA Marketing Management',
                'year_level' => '2nd Year',
                'gwa' => 1.48,
                'gwa_verified' => true,
                'academic_year' => '2025-2026',
                'organization_name' => 'Junior Marketing Association',
                'subsection' => 'pending',
                'status' => 'submitted',
                'requirements' => [
                    'cv' => ['name' => 'CV_Mendoza_Carlo.pdf', 'title' => 'Curriculum Vitae', 'path' => 'tosa/23-70005/cv.pdf'],
                    'good_moral' => ['name' => 'Good_Moral_Carlo.pdf', 'title' => 'Good Moral Certificate', 'path' => 'tosa/23-70005/good_moral.pdf'],
                    'scholastic' => ['name' => 'Grades_1.48.pdf', 'title' => 'Scholastic Record (GWA 1.48)', 'path' => 'tosa/23-70005/scholastic.pdf'],
                    'certificates' => null,
                    'application_docs' => null,
                ],
                'remarks' => '1.48 GWA. Initial submission received; pending certificate verification.',
            ],
            [
                'sr_code' => '23-70006',
                'full_name' => 'Kenji Bautista',
                'email' => 'kenji.bautista@g.batstate-u.edu.ph',
                'college' => 'College of Informatics and Computing Sciences',
                'program' => 'BS Computer Science',
                'year_level' => '3rd Year',
                'gwa' => 1.52,
                'gwa_verified' => true,
                'academic_year' => '2025-2026',
                'organization_name' => 'Association of Computing Machinery (ACM)',
                'subsection' => 'screening',
                'status' => 'submitted',
                'requirements' => [
                    'cv' => ['name' => 'CV_Bautista_Kenji.pdf', 'title' => 'Curriculum Vitae', 'path' => 'tosa/23-70006/cv.pdf'],
                    'good_moral' => ['name' => 'Good_Moral_Kenji.pdf', 'title' => 'Good Moral Certificate', 'path' => 'tosa/23-70006/good_moral.pdf'],
                    'scholastic' => ['name' => 'Grades_1.52.pdf', 'title' => 'Scholastic Record (GWA 1.52)', 'path' => 'tosa/23-70006/scholastic.pdf'],
                    'certificates' => ['name' => 'Certificates_Bautista.pdf', 'title' => 'Certificates with proof of legitimacy', 'path' => 'tosa/23-70006/certificates.pdf'],
                    'application_docs' => null,
                ],
                'remarks' => '1.52 GWA. Algorithmic competitive programmer and mentor.',
            ],
        ];

        foreach ($applicants as $item) {
            TosaApplicant::query()->updateOrCreate(
                ['sr_code' => $item['sr_code']],
                $item
            );
        }
    }
}
