<?php

namespace App\Services;

class ActivityRequirements
{
    public function inCampusRequirements(): array
    {
        return [
            ['key' => 'wpcf', 'title' => 'Waste Policy Compliance Form (WPCF)', 'description' => 'SDO form required before an in-campus activity.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['wpcf', 'waste', 'policy'], 'source_file' => 'Waste-Policy-Compliance-Form-2026 (1).doc'],
            ['key' => 'programme', 'title' => 'Programme / Schedule of Activities', 'description' => 'Final programme with dates, times, venues, and activity flow.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['programme', 'program', 'schedule'], 'source_file' => '2. Programme.docx'],
            ['key' => 'project_proposal', 'title' => 'Project Proposal', 'description' => 'Proposal prepared by the organization president and noted by the adviser.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['project', 'proposal'], 'source_file' => '3. Project Proposal.docx'],
            ['key' => 'budget_proposal', 'title' => 'Budget Proposal', 'description' => 'Itemized funding requirements and source of funds, prepared by the treasurer and noted by the president and adviser.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['budget', 'fund'], 'source_file' => '4. Budget Proposal.docx'],
            ['key' => 'resolution', 'title' => 'Resolution of the Organization', 'description' => 'Officer-signed resolution noting the activity, fees, and fund allocation when applicable.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['resolution'], 'source_file' => '7. Resolution of the Organization .docx'],
            ['key' => 'approved_plan', 'title' => 'Approved Plan of Activities (Attachment I)', 'description' => 'Copy of the plan approved during organization renewal or recognition (Attachment I).', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['approved', 'plan'], 'source_file' => 'Attachment I_ Plan of Activities.docx'],
            ['key' => 'meeting_minutes', 'title' => 'Meeting Minutes and Attendance', 'description' => 'Minutes and attendance from the organization briefing, consultation, or activity preparation meeting.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['minutes', 'attendance', 'briefing'],],
            ['key' => 'faculty_in_charge', 'title' => 'Faculty-in-Charge Designation', 'description' => 'Faculty/adviser designation or dean order with duties before, during, and after the activity and signed conforme.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['faculty', 'in', 'charge', 'designation'], 'source_file' => '14. Faculty-In-Charge.docx'],
            ['key' => 'sample_letter', 'title' => 'Activity Request Letter', 'description' => 'Signed request letter addressed to the appropriate university office.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['sample', 'letter', 'request'], 'source_file' => 'Sample Letter.docx'],
            ['key' => 'medical_clearance', 'title' => 'Medical Clearance', 'description' => 'Signed clearance for physical activities, team-building, sports, or other activities requiring health screening.', 'group' => 'conditional', 'phase' => 'Before activity', 'condition' => 'medical', 'required_on_submit' => true, 'tokens' => ['medical', 'clearance'], 'source_file' => '5. Medical Request Sample Letter.docx'],
            ['key' => 'insurance', 'title' => 'Insurance Coverage', 'description' => 'Proof of participant coverage when the activity involves travel or physical activity.', 'group' => 'conditional', 'phase' => 'Before activity', 'condition' => 'insurance', 'required_on_submit' => true, 'tokens' => ['insurance'], 'source_file' => '6. Insurance Request Sample Letter.docx'],
            ['key' => 'curriculum_vitae', 'title' => 'Curriculum Vitae', 'description' => 'CV of each judge, guest speaker, or external resource person.', 'group' => 'conditional', 'phase' => 'Before activity', 'condition' => 'guest_speaker', 'required_on_submit' => true, 'tokens' => ['curriculum', 'vitae', 'cv'],],
            ['key' => 'waiver', 'title' => 'Notarized Waiver / Parental Consent', 'description' => 'Required when the activity runs beyond 10:00 PM or is scheduled on a weekend.', 'group' => 'conditional', 'phase' => 'Before activity', 'condition' => 'late_or_weekend', 'required_on_submit' => true, 'tokens' => ['waiver', 'consent'],],
            ['key' => 'reservation_form', 'title' => 'University Facility Reservation', 'description' => 'Reservation or permit when using a university facility.', 'group' => 'conditional', 'phase' => 'Before activity', 'condition' => 'university_facility', 'required_on_submit' => true, 'tokens' => ['reservation', 'facility'],],
        ];
    }

    public function localOffCampusRequirements(): array
    {
        return [
            ['key' => 'off_campus_req', 'title' => 'Request for Conduct of Local Off-Campus Activities (FO-REQ-09)', 'description' => 'Official request form with college, participants, itinerary, faculty-in-charge, fees, and approvals.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['req', 'off', 'campus'], 'source_file' => 'BatStateU-FO-REQ-09_Request-for-the-Conduct-of-Local-Off-Campus-Activities-Rev.-02 (1) (1).docx'],
            ['key' => 'checklist_requirements', 'title' => 'CHED Local Off-Campus Checklist', 'description' => 'Checklist showing compliance with CHED Memorandum Order No. 63, Series of 2017.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['checklist', 'requirements'], 'source_file' => 'Checklist of the Requirements.docx'],
            ['key' => 'cert_compliance', 'title' => 'Certificate of Compliance', 'description' => 'Signed certification that the local off-campus activity meets the required safeguards.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['certificate', 'compliance'], 'source_file' => 'Certificate of Compliance (3).docx'],
            ['key' => 'ched_report', 'title' => 'CHED Compliance Report', 'description' => 'Compliance report covering the CHED local off-campus activity requirements.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['ched', 'compliance', 'report'], 'source_file' => 'CHED Compliance Report (1).docx'],
            ['key' => 'course_activities', 'title' => 'Course Activities / Syllabus Relevance', 'description' => 'Course activity plan showing the topic, learning objective, credits, and syllabus relevance.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['course', 'activity', 'syllabus'], 'source_file' => '13. Course Activities (1).docx'],
            ['key' => 'travel_matrix', 'title' => 'Matrix of Travel and Tour / Itinerary', 'description' => 'Complete itinerary with destinations, time, duration, and travel arrangements.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['travel', 'tour', 'itinerary'], 'source_file' => 'Copy of Matrix of Travel and Tour (1).docx'],
            ['key' => 'passenger_matrix', 'title' => 'Matrix of Passenger / Personnel', 'description' => 'Passenger and personnel manifest with emergency contact details.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['passenger', 'personnel', 'matrix'], 'source_file' => 'FORMAT FOR MATRIX OF PASSENGER.docx'],
            ['key' => 'faculty_in_charge', 'title' => 'Faculty-in-Charge / Personnel Designation', 'description' => 'Designation/order naming the faculty or personnel-in-charge and their responsibilities.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['faculty', 'personnel', 'charge', 'designation'], 'source_file' => 'Faculty-In-Charge.docx'],
            ['key' => 'parents_consent', 'title' => 'Notarized Parent / Guardian Consent', 'description' => 'Signed FO-SOA-03 parent or guardian consent/waiver for student participants.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['parent', 'guardian', 'consent', 'waiver'], 'source_file' => 'BatStateU-FO-SOA-03_Parent_s Consent Form (Waiver)_Rev. 01.doc'],
            ['key' => 'curriculum_syllabus', 'title' => 'Curriculum / Syllabus Relevance Proof', 'description' => 'Proof that the destination and activity are relevant to the curriculum, course, or subject.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['curriculum', 'syllabus', 'relevance'],],
            ['key' => 'destination_justification', 'title' => 'Destination Justification', 'description' => 'Report explaining the relevance and suitability of the destination.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['destination', 'justification', 'report'],],
            ['key' => 'handbook_manual', 'title' => 'Updated Handbook / Manual Rule', 'description' => 'Applicable handbook or manual provision governing off-campus activities.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['handbook', 'manual', 'rules'],],
            ['key' => 'first_aid_personnel', 'title' => 'First-Aid-Trained Personnel Certificate', 'description' => 'Certificate or proof that the overall leader/personnel-in-charge has first-aid or medical training.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['first', 'aid', 'training', 'certificate'],],
            ['key' => 'first_aid_kit', 'title' => 'First-Aid Kit Confirmation', 'description' => 'Confirmation or inventory showing a complete first-aid kit will be available.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['first', 'aid', 'kit'],],
            ['key' => 'fee_schedule', 'title' => 'Approved Fees / Fund Source Breakdown', 'description' => 'Approved and disseminated fee schedule or fund-source breakdown for participants.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['fee', 'fund', 'source', 'breakdown'],],
            ['key' => 'insurance', 'title' => 'Individual / Group Insurance', 'description' => 'Proof of individual or group insurance coverage for the off-campus activity.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['insurance'],],
            ['key' => 'orientation_attendance', 'title' => 'Orientation Minutes and Attendance', 'description' => 'Orientation record and attendance before departure.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['orientation', 'attendance', 'minutes'],],
            ['key' => 'consultation_record', 'title' => 'Consultation Record', 'description' => 'Consultation minutes with signatures of students, parents, faculty, or other required parties.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['consultation', 'minutes'],],
            ['key' => 'announcement_letters', 'title' => 'Advance Announcement / Notice Letters', 'description' => 'Notices to students, faculty, and parents issued one to two months before the activity when applicable.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['announcement', 'notice', 'letter'],],
            ['key' => 'briefing_itinerary', 'title' => 'Briefing Materials and Itinerary', 'description' => 'Participant briefing materials and final itinerary.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['briefing', 'itinerary', 'information'],],
            ['key' => 'learning_journal_format', 'title' => 'Learning Journal Format', 'description' => 'Journal or reflection format that participants will complete for the learning activity.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['learning', 'journal', 'reflection'],],
            ['key' => 'emergency_plan', 'title' => 'Emergency Preparedness Plan', 'description' => 'Emergency response plan with contacts, procedures, and escalation arrangements.', 'group' => 'before', 'phase' => 'Before activity', 'condition' => null, 'required_on_submit' => true, 'tokens' => ['emergency', 'preparedness', 'safety', 'plan'],],
            ['key' => 'medical_clearance', 'title' => 'Medical Clearance', 'description' => 'Medical clearance signed by the HEI or government physician when appropriate.', 'group' => 'conditional', 'phase' => 'Before activity', 'condition' => 'medical', 'required_on_submit' => true, 'tokens' => ['medical', 'clearance'],],
            ['key' => 'vehicle_registration', 'title' => 'Mobility Documents / Vehicle Registration', 'description' => 'Vehicle registration, insurance, driver license, roadworthiness, franchise, or permit documents as applicable.', 'group' => 'conditional', 'phase' => 'Before activity', 'condition' => 'transport', 'required_on_submit' => true, 'tokens' => ['vehicle', 'registration', 'driver', 'franchise', 'permit'],],
            ['key' => 'tour_operator_cert', 'title' => 'DOT Tour Operator Accreditation and Contract', 'description' => 'DOT accreditation, transport/guide details, approved itinerary, and contract for a travel/tour operator.', 'group' => 'conditional', 'phase' => 'Before activity', 'condition' => 'tour_operator', 'required_on_submit' => true, 'tokens' => ['tour', 'operator', 'dot', 'contract', 'accreditation'],],
            ['key' => 'lgu_ngo_coordination', 'title' => 'LGU / NGO Coordination Letter', 'description' => 'Coordination letter or acknowledgement when an LGU, NGO, host, or external partner is involved.', 'group' => 'conditional', 'phase' => 'Before activity', 'condition' => 'external_coordination', 'required_on_submit' => true, 'tokens' => ['lgu', 'ngo', 'coordination', 'acknowledgement'],],
            ['key' => 'during_attendance', 'title' => 'During-Activity Attendance and Supervision Record', 'description' => 'Assembly-to-debriefing attendance and supervision record to be completed during the activity.', 'group' => 'during', 'phase' => 'During activity', 'condition' => null, 'required_on_submit' => false, 'tokens' => ['attendance', 'supervision', 'during'],],
            ['key' => 'travel_contract', 'title' => 'Transport / Third-Party Contract', 'description' => 'Signed contract or agreement with the transport provider, when applicable.', 'group' => 'during', 'phase' => 'During activity', 'condition' => null, 'required_on_submit' => false, 'tokens' => ['transport', 'contract', 'agreement'],],
            ['key' => 'learning_journals', 'title' => 'Completed Learning Journals / Grades', 'description' => 'Participant learning journals or grades after the activity.', 'group' => 'after', 'phase' => 'After activity', 'condition' => null, 'required_on_submit' => false, 'tokens' => ['learning', 'journal', 'grades'],],
            ['key' => 'assessment_expense_report', 'title' => 'Assessment and Expense Report', 'description' => 'Faculty assessment/evaluation report including the breakdown of expenses.', 'group' => 'after', 'phase' => 'After activity', 'condition' => null, 'required_on_submit' => false, 'tokens' => ['assessment', 'evaluation', 'expense', 'report'],],
            ['key' => 'expenditure_report', 'title' => 'Expenditure Report', 'description' => 'Post-activity expenditure report with supporting receipts.', 'group' => 'after', 'phase' => 'After activity', 'condition' => null, 'required_on_submit' => false, 'tokens' => ['expenditure', 'expense', 'report'],],
            ['key' => 'debriefing_report', 'title' => 'Debriefing Report', 'description' => 'Post-activity debriefing report and action points.', 'group' => 'after', 'phase' => 'After activity', 'condition' => null, 'required_on_submit' => false, 'tokens' => ['debriefing', 'debrief', 'report'],],
        ];
    }
}

